[project]
name = "ml-data-engineering-habits"
version = "0.1.0"
description = "ML Data Engineering Habits"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dvc>=3.63.0",
    "pandas>=2.3.3",
    "pandera>=0.26.1",
    "scipy>=1.16.2",
]
